services:
  - mysql
  - postgresql
  - SQLITE3
  
  

before_install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh
  - export PATH="/home/travis/.deno/bin:$PATH"

script:
  - deno test --allow-net  --allow-read --allow-write -c tsconfig.json test.ts 
